# This file instructs Redocly's linter to ignore the rules contained for specific parts of your API.
# See https://redocly.com/docs/cli/ for more information.
openapi.json:
  no-empty-servers:
    - '#/openapi'
  info-license:
    - '#/info'
  no-identical-paths:
    - '#/paths/~1clinical-sessions~1group~1{group_id}'
  no-ambiguous-paths:
    - '#/paths/~1clinical-sessions~1group~1{group_id}'
    - '#/paths/~1clinical-sessions~1{session_id}~1all-status'
    - '#/paths/~1clinical-sessions~1{session_id}~1group-notes'
    - '#/paths/~1clinical-sessions~1{session_id}~1process'
    - '#/paths/~1clinical-sessions~1{session_id}~1transcripts'
    - '#/paths/~1clinical-sessions~1{session_id}~1workflows'
  operation-4xx-response:
    - '#/paths/~1logout/post/responses'
    - '#/paths/~1current-user/get/responses'
    - '#/paths/~1enterprises/get/responses'
    - '#/paths/~1centers/get/responses'
    - '#/paths/~1billing~1subscription/get/responses'
    - '#/paths/~1billing~1create-setup-intent/post/responses'
    - '#/paths/~1billing~1internal~1centers/get/responses'
    - '#/paths/~1webhooks~1stripe/post/responses'
    - '#/paths/~1patients/get/responses'
    - '#/paths/~1clinical-sessions/post/responses'
    - '#/paths/~1workflows~1backfill-groupings/post/responses'
    - '#/paths/~1dashboard~1users-today/get/responses'
    - '#/paths/~1dashboard~1dau/get/responses'
    - '#/paths/~1dashboard~1sessions-today-by-user/get/responses'
    - '#/paths/~1dashboard~1all-centers/get/responses'
    - '#/paths/~1dashboard~1general-metrics/get/responses'
    - '#/paths/~1internal~1require-update/post/responses'
    - '#/paths/~1internal~1backfill-progress/post/responses'
    - '#/paths/~1internal~1backfill-prompts/post/responses'
    - '#/paths/~1internal~1toggle-populate-model/post/responses'
    - '#/paths/~1internal~1backfill-s3-file-keys/post/responses'
    - '#/paths/~1internal~1backfill-group-workflow/post/responses'
    - '#/paths/~1extension~1latest/get/responses'
    - '#/paths/~1fhir-query~1health/get/responses'
    - '#/paths/~1fhir-query~1chat~1start/post/responses'
    - '#/paths/~1perspectives-query~1health/get/responses'
    - '#/paths/~1charts/get/responses'
    - '#/paths/~1charts~1questions/get/responses'
    - '#/paths/~1charts~1seed-questions/post/responses'
    - '#/paths/~1/get/responses'
  security-defined:
    - '#/paths/~1login/post'
    - '#/paths/~1login~1bestnotes/post'
    - '#/paths/~1signup~1admin/post'
    - '#/paths/~1auth~1password-reset~1request/post'
    - '#/paths/~1auth~1password-reset~1confirm/post'
    - '#/paths/~1refresh/post'
    - '#/paths/~1webhooks~1stripe/post'
    - '#/paths/~1/get'
