# This file instructs Redocly's linter to ignore the rules contained for specific parts of your API.
# See https://redocly.com/docs/cli/ for more information.
openapi.json:
  no-empty-servers:
    - '#/openapi'
  info-license:
    - '#/info'
  operation-4xx-response:
    - '#/paths/~1logout/post/responses'
    - '#/paths/~1current-user/get/responses'
    - '#/paths/~1unprotected-route/get/responses'
    - '#/paths/~1populate-settings/get/responses'
    - '#/paths/~1centers/get/responses'
    - '#/paths/~1patients/get/responses'
    - '#/paths/~1clinical-sessions/post/responses'
    - '#/paths/~1clinical-sessions~1workflows/get/responses'
    - '#/paths/~1workflows~1backfill-groupings/post/responses'
    - '#/paths/~1workflows~1debug~1thread-pools/get/responses'
    - '#/paths/~1payment~1cancel/get/responses'
    - '#/paths/~1dashboard~1users-today/get/responses'
    - '#/paths/~1dashboard~1dau/get/responses'
    - '#/paths/~1dashboard~1sessions-today-by-user/get/responses'
    - '#/paths/~1dashboard~1all-centers/get/responses'
    - '#/paths/~1dashboard~1general-metrics/get/responses'
    - '#/paths/~1dashboard~1last-use/get/responses'
    - '#/paths/~1dashboard~1weekly-users/get/responses'
    - '#/paths/~1dashboard~1all-users/get/responses'
    - '#/paths/~1dashboard~1all-sessions/get/responses'
    - '#/paths/~1dashboard~1sessions-today/get/responses'
    - '#/paths/~1dashboard~1health/get/responses'
    - '#/paths/~1internal~1test-prompt-clear/post/responses'
    - '#/paths/~1internal~1conversations/get/responses'
    - '#/paths/~1internal~1require-update/post/responses'
    - '#/paths/~1internal~1test-jobs/get/responses'
    - '#/paths/~1internal~1test-jobs~1clear-all/delete/responses'
    - '#/paths/~1internal~1backfill-progress/post/responses'
    - '#/paths/~1extension~1update-required/get/responses'
    - '#/paths/~1extension~1latest/get/responses'
    - '#/paths/~1/get/responses'
  security-defined:
    - '#/paths/~1login/post'
    - '#/paths/~1signup/post'
    - '#/paths/~1signup~1admin/post'
    - '#/paths/~1create-center/post'
    - '#/paths/~1users~1clinicians~1bulk/post'
    - '#/paths/~1users~1create/post'
    - '#/paths/~1unprotected-route/get'
    - '#/paths/~1auth~1password-reset~1request/post'
    - '#/paths/~1auth~1password-reset~1confirm/post'
    - '#/paths/~1refresh/post'
    - '#/paths/~1centers~1{center_id}~1display-consent/post'
    - '#/paths/~1workflows~1regeneration-tasks~1batch-status/post'
    - '#/paths/~1workflows~1debug~1thread-pools/get'
    - '#/paths/~1payment~1centers/post'
    - '#/paths/~1payment~1centers~1{center_id}/delete'
    - '#/paths/~1payment~1webhook/post'
    - '#/paths/~1payment~1create-checkout-session~1{center_id}/post'
    - '#/paths/~1payment~1subscription-status~1{center_id}/get'
    - '#/paths/~1payment~1success/get'
    - '#/paths/~1payment~1cancel/get'
    - '#/paths/~1payment~1update-subscription~1{center_id}/post'
    - '#/paths/~1payment~1billing-info~1{center_id}/get'
    - '#/paths/~1payment~1update-payment-method~1{center_id}/post'
    - '#/paths/~1payment~1payment-methods~1{center_id}/get'
    - '#/paths/~1payment~1create-payment-intent~1{center_id}/post'
    - '#/paths/~1payment~1centers~1{center_id}~1compliance-metadata/post'
    - '#/paths/~1dashboard~1users-today/get'
    - '#/paths/~1dashboard~1dau/get'
    - '#/paths/~1dashboard~1sessions-today-by-user/get'
    - '#/paths/~1dashboard~1all-centers/get'
    - '#/paths/~1dashboard~1center-metrics/get'
    - '#/paths/~1dashboard~1crm-metrics/get'
    - '#/paths/~1dashboard~1crm/get'
    - '#/paths/~1dashboard~1user-sessions~1{user_id}/get'
    - '#/paths/~1dashboard~1users-with-centers/get'
    - '#/paths/~1dashboard~1general-metrics/get'
    - '#/paths/~1dashboard~1users~1{user_id}~1ignore/put'
    - '#/paths/~1dashboard~1users~1{user_id}~1notes/put'
    - '#/paths/~1dashboard~1session-stats~1{center_id}/get'
    - '#/paths/~1dashboard~1user-stats~1{center_id}/get'
    - '#/paths/~1dashboard~1user-sessions-meta~1{user_id}/get'
    - '#/paths/~1dashboard~1note-audio~1{workflow_instance_id}/get'
    - '#/paths/~1dashboard~1centers~1{center_id}~1emrsetup/get'
    - '#/paths/~1dashboard~1centers~1{center_id}~1emrsetup/put'
    - '#/paths/~1dashboard~1last-use/get'
    - '#/paths/~1dashboard~1weekly-users/get'
    - '#/paths/~1dashboard~1all-users/get'
    - '#/paths/~1dashboard~1all-sessions/get'
    - '#/paths/~1dashboard~1sessions-today/get'
    - '#/paths/~1dashboard~1health/get'
    - '#/paths/~1dashboard~1test-populate/post'
    - '#/paths/~1internal~1test-prompt/post'
    - '#/paths/~1internal~1test-prompt-result~1{job_id}/get'
    - '#/paths/~1internal~1test-prompt-clear/post'
    - '#/paths/~1internal~1conversations/get'
    - '#/paths/~1internal~1prompt/get'
    - '#/paths/~1internal~1recover-transcript/post'
    - '#/paths/~1internal~1require-update/post'
    - '#/paths/~1internal~1toggle-user-update/post'
    - '#/paths/~1internal~1sync-db/get'
    - '#/paths/~1internal~1test-jobs/get'
    - '#/paths/~1internal~1test-job/post'
    - '#/paths/~1internal~1test-jobs~1clear-all/delete'
    - '#/paths/~1internal~1test-jobs~1{job_id}/delete'
    - '#/paths/~1internal~1test-llm/post'
    - '#/paths/~1internal~1test-openai/post'
    - '#/paths/~1internal~1backfill-progress/post'
    - '#/paths/~1emails~1send/post'
    - '#/paths/~1/get'
