import { config } from "@/modules/shared/config";
import createClient, { Middleware } from "openapi-fetch";
import type { paths } from "@/modules/shared/schema"; // generated by openapi-typescript
import { getAuthToken } from "@/modules/auth/auth.utils";


const authMiddleware: Middleware = {
    async onRequest({ request, options }) {
        const accessToken = await getAuthToken();
        if (accessToken) {
            request.headers.set("Authorization", `Bearer ${accessToken}`);
        } else {
            console.error("No auth token found");
        }

        return request;
    },
    async onResponse({ request, response, options }) {
        return response;
    },
};
const loggingMiddleware: Middleware = {
    async onRequest({ request, options }) {
        return request;
    },
    async onResponse({ request, response, options }) {
        const { body, ...resOptions } = response;
        return response;
    },
    async onError({ error }) {
        console.error("API Error:", error);
        return;
    },
};

const errorMiddleware: Middleware = {
    async onResponse({ response }) {
        if (!response.ok) {
            const data = await response.clone().json();
            throw new Error(data?.error || "UNKNOWN_ERROR");
        }
        return response;
    },
};


export const fastapi = createClient<paths>({ baseUrl: config.apiUrl });

fastapi.use(loggingMiddleware);
fastapi.use(errorMiddleware);
fastapi.use(authMiddleware);
